version: '3.8'

services:

  backend:
    image: example-backend
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 8080:8080

  frontend:
    image: example-frontend
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 5000:5000
