version: '3.8'

services:
  backend:
    image: example-backend
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
    container_name: back

  frontend:
    image: example-frontend
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
    container_name: front

  redis:
    image: redis
    container_name: redis
